### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-domozhyrskyi#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
3) Відомо, що Git-система контроля версій використовує запити Pull Request. 
Поясніть, будь ласка, як використання такого запиту може підвищити 
безпеку процесів створення програмного продукту?

**Comment by mih444** [comment]
Запити Pull Request (PR) в Git підвищують безпеку процесів створення програмного продукту шляхом забезпечення наступних важливих аспектів:
PR дозволяють команді переглядати та аудитувати зміни в коді перед їх об'єднанням з основною гілкою, допомагаючи виявити можливі безпекові проблеми та вимоги до безпеки.
Автоматичні тести та перевірки, які активуються під час створення PR, можуть виявити безпекові проблеми та допомогти у їх виправленні.
Записи комітів та коментарі в PR допомагають відстежувати, хто вніс зміни та деталі їх внесення, що сприяє відповідальності та аудиту.
Контроль доступу до PR дозволяє обмежити права доступу до коду, зменшуючи ризик несанкціонованого доступу.
Можливість аналізу залежностей та відслідковування вразливостей в них допомагає забезпечити безпеку через керування використовуваними бібліотеками та компонентами.
